// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: spotinstrumentservice/v1/spot_instrument.proto

// Package spotinstrumentservice.v1 defines the public gRPC contract for
// SpotInstrumentService: the catalog of tradable spot pairs and their
// current rates.

package spotinstrumentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InstrumentStatus reflects whether an instrument is currently tradable.
type InstrumentStatus int32

const (
	// INSTRUMENT_STATUS_UNSPECIFIED is the zero value and should never be
	// assigned to a real instrument.
	InstrumentStatus_INSTRUMENT_STATUS_UNSPECIFIED InstrumentStatus = 0
	// INSTRUMENT_STATUS_ACTIVE instruments accept new orders.
	InstrumentStatus_INSTRUMENT_STATUS_ACTIVE InstrumentStatus = 1
	// INSTRUMENT_STATUS_PAUSED instruments are temporarily halted; existing
	// orders are unaffected but new orders should be rejected by OrderService.
	InstrumentStatus_INSTRUMENT_STATUS_PAUSED InstrumentStatus = 2
	// INSTRUMENT_STATUS_DELISTED instruments are permanently retired via
	// ArchiveInstrument and no longer accept new orders.
	InstrumentStatus_INSTRUMENT_STATUS_DELISTED InstrumentStatus = 3
)

// Enum value maps for InstrumentStatus.
var (
	InstrumentStatus_name = map[int32]string{
		0: "INSTRUMENT_STATUS_UNSPECIFIED",
		1: "INSTRUMENT_STATUS_ACTIVE",
		2: "INSTRUMENT_STATUS_PAUSED",
		3: "INSTRUMENT_STATUS_DELISTED",
	}
	InstrumentStatus_value = map[string]int32{
		"INSTRUMENT_STATUS_UNSPECIFIED": 0,
		"INSTRUMENT_STATUS_ACTIVE":      1,
		"INSTRUMENT_STATUS_PAUSED":      2,
		"INSTRUMENT_STATUS_DELISTED":    3,
	}
)

func (x InstrumentStatus) Enum() *InstrumentStatus {
	p := new(InstrumentStatus)
	*p = x
	return p
}

func (x InstrumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstrumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_spotinstrumentservice_v1_spot_instrument_proto_enumTypes[0].Descriptor()
}

func (InstrumentStatus) Type() protoreflect.EnumType {
	return &file_spotinstrumentservice_v1_spot_instrument_proto_enumTypes[0]
}

func (x InstrumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstrumentStatus.Descriptor instead.
func (InstrumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{0}
}

// Instrument represents a single tradable spot pair, e.g. BTCUSDT.
//
// Monetary fields (min_order_size, current_rate) are represented as decimal
// strings, not double, to avoid floating-point rounding errors on values
// that represent real money.
type Instrument struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// symbol is the combined trading symbol, e.g. "BTCUSDT".
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// base_asset is the asset being bought/sold, e.g. "BTC".
	BaseAsset string `protobuf:"bytes,3,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	// quote_asset is the asset used to price base_asset, e.g. "USDT".
	QuoteAsset string `protobuf:"bytes,4,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	// price_precision is the number of decimal digits allowed in order prices
	// for this instrument.
	PricePrecision int32 `protobuf:"varint,5,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	// quantity_precision is the number of decimal digits allowed in order
	// quantities for this instrument.
	QuantityPrecision int32 `protobuf:"varint,6,opt,name=quantity_precision,json=quantityPrecision,proto3" json:"quantity_precision,omitempty"`
	// min_order_size is the minimum tradable quantity, as a decimal string.
	MinOrderSize string `protobuf:"bytes,7,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"`
	// current_rate is the latest known exchange rate, as a decimal string.
	CurrentRate   string                 `protobuf:"bytes,8,opt,name=current_rate,json=currentRate,proto3" json:"current_rate,omitempty"`
	Status        InstrumentStatus       `protobuf:"varint,9,opt,name=status,proto3,enum=spotinstrumentservice.v1.InstrumentStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{0}
}

func (x *Instrument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instrument) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Instrument) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *Instrument) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *Instrument) GetPricePrecision() int32 {
	if x != nil {
		return x.PricePrecision
	}
	return 0
}

func (x *Instrument) GetQuantityPrecision() int32 {
	if x != nil {
		return x.QuantityPrecision
	}
	return 0
}

func (x *Instrument) GetMinOrderSize() string {
	if x != nil {
		return x.MinOrderSize
	}
	return ""
}

func (x *Instrument) GetCurrentRate() string {
	if x != nil {
		return x.CurrentRate
	}
	return ""
}

func (x *Instrument) GetStatus() InstrumentStatus {
	if x != nil {
		return x.Status
	}
	return InstrumentStatus_INSTRUMENT_STATUS_UNSPECIFIED
}

func (x *Instrument) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Instrument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateInstrumentRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseAsset         string                 `protobuf:"bytes,2,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset        string                 `protobuf:"bytes,3,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	PricePrecision    int32                  `protobuf:"varint,4,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	QuantityPrecision int32                  `protobuf:"varint,5,opt,name=quantity_precision,json=quantityPrecision,proto3" json:"quantity_precision,omitempty"`
	MinOrderSize      string                 `protobuf:"bytes,6,opt,name=min_order_size,json=minOrderSize,proto3" json:"min_order_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateInstrumentRequest) Reset() {
	*x = CreateInstrumentRequest{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstrumentRequest) ProtoMessage() {}

func (x *CreateInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstrumentRequest.ProtoReflect.Descriptor instead.
func (*CreateInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstrumentRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateInstrumentRequest) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *CreateInstrumentRequest) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *CreateInstrumentRequest) GetPricePrecision() int32 {
	if x != nil {
		return x.PricePrecision
	}
	return 0
}

func (x *CreateInstrumentRequest) GetQuantityPrecision() int32 {
	if x != nil {
		return x.QuantityPrecision
	}
	return 0
}

func (x *CreateInstrumentRequest) GetMinOrderSize() string {
	if x != nil {
		return x.MinOrderSize
	}
	return ""
}

type CreateInstrumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    *Instrument            `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstrumentResponse) Reset() {
	*x = CreateInstrumentResponse{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstrumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstrumentResponse) ProtoMessage() {}

func (x *CreateInstrumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstrumentResponse.ProtoReflect.Descriptor instead.
func (*CreateInstrumentResponse) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInstrumentResponse) GetInstrument() *Instrument {
	if x != nil {
		return x.Instrument
	}
	return nil
}

type GetInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentRequest) Reset() {
	*x = GetInstrumentRequest{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentRequest) ProtoMessage() {}

func (x *GetInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentRequest.ProtoReflect.Descriptor instead.
func (*GetInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{3}
}

func (x *GetInstrumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetInstrumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    *Instrument            `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstrumentResponse) Reset() {
	*x = GetInstrumentResponse{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstrumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstrumentResponse) ProtoMessage() {}

func (x *GetInstrumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstrumentResponse.ProtoReflect.Descriptor instead.
func (*GetInstrumentResponse) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{4}
}

func (x *GetInstrumentResponse) GetInstrument() *Instrument {
	if x != nil {
		return x.Instrument
	}
	return nil
}

type ListInstrumentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status_filter restricts the result to instruments with this status.
	// Unset returns instruments of all statuses.
	StatusFilter  *InstrumentStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=spotinstrumentservice.v1.InstrumentStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstrumentsRequest) Reset() {
	*x = ListInstrumentsRequest{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstrumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstrumentsRequest) ProtoMessage() {}

func (x *ListInstrumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstrumentsRequest.ProtoReflect.Descriptor instead.
func (*ListInstrumentsRequest) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{5}
}

func (x *ListInstrumentsRequest) GetStatusFilter() InstrumentStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return InstrumentStatus_INSTRUMENT_STATUS_UNSPECIFIED
}

type ListInstrumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruments   []*Instrument          `protobuf:"bytes,1,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstrumentsResponse) Reset() {
	*x = ListInstrumentsResponse{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstrumentsResponse) ProtoMessage() {}

func (x *ListInstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstrumentsResponse.ProtoReflect.Descriptor instead.
func (*ListInstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{6}
}

func (x *ListInstrumentsResponse) GetInstruments() []*Instrument {
	if x != nil {
		return x.Instruments
	}
	return nil
}

type ArchiveInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveInstrumentRequest) Reset() {
	*x = ArchiveInstrumentRequest{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveInstrumentRequest) ProtoMessage() {}

func (x *ArchiveInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveInstrumentRequest.ProtoReflect.Descriptor instead.
func (*ArchiveInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{7}
}

func (x *ArchiveInstrumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ArchiveInstrumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    *Instrument            `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveInstrumentResponse) Reset() {
	*x = ArchiveInstrumentResponse{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveInstrumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveInstrumentResponse) ProtoMessage() {}

func (x *ArchiveInstrumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveInstrumentResponse.ProtoReflect.Descriptor instead.
func (*ArchiveInstrumentResponse) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveInstrumentResponse) GetInstrument() *Instrument {
	if x != nil {
		return x.Instrument
	}
	return nil
}

type UpdateRateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// rate is the new exchange rate, as a decimal string, e.g. "43521.87".
	Rate          string `protobuf:"bytes,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRateRequest) Reset() {
	*x = UpdateRateRequest{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRateRequest) ProtoMessage() {}

func (x *UpdateRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRateRequest) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRateRequest) GetRate() string {
	if x != nil {
		return x.Rate
	}
	return ""
}

type UpdateRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instrument    *Instrument            `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRateResponse) Reset() {
	*x = UpdateRateResponse{}
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRateResponse) ProtoMessage() {}

func (x *UpdateRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRateResponse.ProtoReflect.Descriptor instead.
func (*UpdateRateResponse) Descriptor() ([]byte, []int) {
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRateResponse) GetInstrument() *Instrument {
	if x != nil {
		return x.Instrument
	}
	return nil
}

var File_spotinstrumentservice_v1_spot_instrument_proto protoreflect.FileDescriptor

const file_spotinstrumentservice_v1_spot_instrument_proto_rawDesc = "" +
	"\n" +
	".spotinstrumentservice/v1/spot_instrument.proto\x12\x18spotinstrumentservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xcf\x03\n" +
	"\n" +
	"Instrument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x03 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x04 \x01(\tR\n" +
	"quoteAsset\x12'\n" +
	"\x0fprice_precision\x18\x05 \x01(\x05R\x0epricePrecision\x12-\n" +
	"\x12quantity_precision\x18\x06 \x01(\x05R\x11quantityPrecision\x12$\n" +
	"\x0emin_order_size\x18\a \x01(\tR\fminOrderSize\x12!\n" +
	"\fcurrent_rate\x18\b \x01(\tR\vcurrentRate\x12B\n" +
	"\x06status\x18\t \x01(\x0e2*.spotinstrumentservice.v1.InstrumentStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xa5\x02\n" +
	"\x17CreateInstrumentRequest\x12\x1f\n" +
	"\x06symbol\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06symbol\x12&\n" +
	"\n" +
	"base_asset\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tbaseAsset\x12(\n" +
	"\vquote_asset\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"quoteAsset\x120\n" +
	"\x0fprice_precision\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x0epricePrecision\x126\n" +
	"\x12quantity_precision\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x11quantityPrecision\x12-\n" +
	"\x0emin_order_size\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\fminOrderSize\"`\n" +
	"\x18CreateInstrumentResponse\x12D\n" +
	"\n" +
	"instrument\x18\x01 \x01(\v2$.spotinstrumentservice.v1.InstrumentR\n" +
	"instrument\"0\n" +
	"\x14GetInstrumentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"]\n" +
	"\x15GetInstrumentResponse\x12D\n" +
	"\n" +
	"instrument\x18\x01 \x01(\v2$.spotinstrumentservice.v1.InstrumentR\n" +
	"instrument\"\x80\x01\n" +
	"\x16ListInstrumentsRequest\x12T\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2*.spotinstrumentservice.v1.InstrumentStatusH\x00R\fstatusFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filter\"a\n" +
	"\x17ListInstrumentsResponse\x12F\n" +
	"\vinstruments\x18\x01 \x03(\v2$.spotinstrumentservice.v1.InstrumentR\vinstruments\"4\n" +
	"\x18ArchiveInstrumentRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"a\n" +
	"\x19ArchiveInstrumentResponse\x12D\n" +
	"\n" +
	"instrument\x18\x01 \x01(\v2$.spotinstrumentservice.v1.InstrumentR\n" +
	"instrument\"J\n" +
	"\x11UpdateRateRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x1b\n" +
	"\x04rate\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04rate\"Z\n" +
	"\x12UpdateRateResponse\x12D\n" +
	"\n" +
	"instrument\x18\x01 \x01(\v2$.spotinstrumentservice.v1.InstrumentR\n" +
	"instrument*\x91\x01\n" +
	"\x10InstrumentStatus\x12!\n" +
	"\x1dINSTRUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INSTRUMENT_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18INSTRUMENT_STATUS_PAUSED\x10\x02\x12\x1e\n" +
	"\x1aINSTRUMENT_STATUS_DELISTED\x10\x032\xed\x04\n" +
	"\x15SpotInstrumentService\x12{\n" +
	"\x10CreateInstrument\x121.spotinstrumentservice.v1.CreateInstrumentRequest\x1a2.spotinstrumentservice.v1.CreateInstrumentResponse\"\x00\x12r\n" +
	"\rGetInstrument\x12..spotinstrumentservice.v1.GetInstrumentRequest\x1a/.spotinstrumentservice.v1.GetInstrumentResponse\"\x00\x12x\n" +
	"\x0fListInstruments\x120.spotinstrumentservice.v1.ListInstrumentsRequest\x1a1.spotinstrumentservice.v1.ListInstrumentsResponse\"\x00\x12~\n" +
	"\x11ArchiveInstrument\x122.spotinstrumentservice.v1.ArchiveInstrumentRequest\x1a3.spotinstrumentservice.v1.ArchiveInstrumentResponse\"\x00\x12i\n" +
	"\n" +
	"UpdateRate\x12+.spotinstrumentservice.v1.UpdateRateRequest\x1a,.spotinstrumentservice.v1.UpdateRateResponse\"\x00B+Z)spotinstrumentservice/v1;spotinstrumentv1b\x06proto3"

var (
	file_spotinstrumentservice_v1_spot_instrument_proto_rawDescOnce sync.Once
	file_spotinstrumentservice_v1_spot_instrument_proto_rawDescData []byte
)

func file_spotinstrumentservice_v1_spot_instrument_proto_rawDescGZIP() []byte {
	file_spotinstrumentservice_v1_spot_instrument_proto_rawDescOnce.Do(func() {
		file_spotinstrumentservice_v1_spot_instrument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spotinstrumentservice_v1_spot_instrument_proto_rawDesc), len(file_spotinstrumentservice_v1_spot_instrument_proto_rawDesc)))
	})
	return file_spotinstrumentservice_v1_spot_instrument_proto_rawDescData
}

var file_spotinstrumentservice_v1_spot_instrument_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_spotinstrumentservice_v1_spot_instrument_proto_goTypes = []any{
	(InstrumentStatus)(0),             // 0: spotinstrumentservice.v1.InstrumentStatus
	(*Instrument)(nil),                // 1: spotinstrumentservice.v1.Instrument
	(*CreateInstrumentRequest)(nil),   // 2: spotinstrumentservice.v1.CreateInstrumentRequest
	(*CreateInstrumentResponse)(nil),  // 3: spotinstrumentservice.v1.CreateInstrumentResponse
	(*GetInstrumentRequest)(nil),      // 4: spotinstrumentservice.v1.GetInstrumentRequest
	(*GetInstrumentResponse)(nil),     // 5: spotinstrumentservice.v1.GetInstrumentResponse
	(*ListInstrumentsRequest)(nil),    // 6: spotinstrumentservice.v1.ListInstrumentsRequest
	(*ListInstrumentsResponse)(nil),   // 7: spotinstrumentservice.v1.ListInstrumentsResponse
	(*ArchiveInstrumentRequest)(nil),  // 8: spotinstrumentservice.v1.ArchiveInstrumentRequest
	(*ArchiveInstrumentResponse)(nil), // 9: spotinstrumentservice.v1.ArchiveInstrumentResponse
	(*UpdateRateRequest)(nil),         // 10: spotinstrumentservice.v1.UpdateRateRequest
	(*UpdateRateResponse)(nil),        // 11: spotinstrumentservice.v1.UpdateRateResponse
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
}
var file_spotinstrumentservice_v1_spot_instrument_proto_depIdxs = []int32{
	0,  // 0: spotinstrumentservice.v1.Instrument.status:type_name -> spotinstrumentservice.v1.InstrumentStatus
	12, // 1: spotinstrumentservice.v1.Instrument.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: spotinstrumentservice.v1.Instrument.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: spotinstrumentservice.v1.CreateInstrumentResponse.instrument:type_name -> spotinstrumentservice.v1.Instrument
	1,  // 4: spotinstrumentservice.v1.GetInstrumentResponse.instrument:type_name -> spotinstrumentservice.v1.Instrument
	0,  // 5: spotinstrumentservice.v1.ListInstrumentsRequest.status_filter:type_name -> spotinstrumentservice.v1.InstrumentStatus
	1,  // 6: spotinstrumentservice.v1.ListInstrumentsResponse.instruments:type_name -> spotinstrumentservice.v1.Instrument
	1,  // 7: spotinstrumentservice.v1.ArchiveInstrumentResponse.instrument:type_name -> spotinstrumentservice.v1.Instrument
	1,  // 8: spotinstrumentservice.v1.UpdateRateResponse.instrument:type_name -> spotinstrumentservice.v1.Instrument
	2,  // 9: spotinstrumentservice.v1.SpotInstrumentService.CreateInstrument:input_type -> spotinstrumentservice.v1.CreateInstrumentRequest
	4,  // 10: spotinstrumentservice.v1.SpotInstrumentService.GetInstrument:input_type -> spotinstrumentservice.v1.GetInstrumentRequest
	6,  // 11: spotinstrumentservice.v1.SpotInstrumentService.ListInstruments:input_type -> spotinstrumentservice.v1.ListInstrumentsRequest
	8,  // 12: spotinstrumentservice.v1.SpotInstrumentService.ArchiveInstrument:input_type -> spotinstrumentservice.v1.ArchiveInstrumentRequest
	10, // 13: spotinstrumentservice.v1.SpotInstrumentService.UpdateRate:input_type -> spotinstrumentservice.v1.UpdateRateRequest
	3,  // 14: spotinstrumentservice.v1.SpotInstrumentService.CreateInstrument:output_type -> spotinstrumentservice.v1.CreateInstrumentResponse
	5,  // 15: spotinstrumentservice.v1.SpotInstrumentService.GetInstrument:output_type -> spotinstrumentservice.v1.GetInstrumentResponse
	7,  // 16: spotinstrumentservice.v1.SpotInstrumentService.ListInstruments:output_type -> spotinstrumentservice.v1.ListInstrumentsResponse
	9,  // 17: spotinstrumentservice.v1.SpotInstrumentService.ArchiveInstrument:output_type -> spotinstrumentservice.v1.ArchiveInstrumentResponse
	11, // 18: spotinstrumentservice.v1.SpotInstrumentService.UpdateRate:output_type -> spotinstrumentservice.v1.UpdateRateResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_spotinstrumentservice_v1_spot_instrument_proto_init() }
func file_spotinstrumentservice_v1_spot_instrument_proto_init() {
	if File_spotinstrumentservice_v1_spot_instrument_proto != nil {
		return
	}
	file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spotinstrumentservice_v1_spot_instrument_proto_rawDesc), len(file_spotinstrumentservice_v1_spot_instrument_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_spotinstrumentservice_v1_spot_instrument_proto_goTypes,
		DependencyIndexes: file_spotinstrumentservice_v1_spot_instrument_proto_depIdxs,
		EnumInfos:         file_spotinstrumentservice_v1_spot_instrument_proto_enumTypes,
		MessageInfos:      file_spotinstrumentservice_v1_spot_instrument_proto_msgTypes,
	}.Build()
	File_spotinstrumentservice_v1_spot_instrument_proto = out.File
	file_spotinstrumentservice_v1_spot_instrument_proto_goTypes = nil
	file_spotinstrumentservice_v1_spot_instrument_proto_depIdxs = nil
}
