// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: spotinstrumentservice/v1/spot_instrument.proto

// Package spotinstrumentservice.v1 defines the public gRPC contract for
// SpotInstrumentService: the catalog of tradable spot pairs and their
// current rates.

package spotinstrumentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpotInstrumentService_CreateInstrument_FullMethodName  = "/spotinstrumentservice.v1.SpotInstrumentService/CreateInstrument"
	SpotInstrumentService_GetInstrument_FullMethodName     = "/spotinstrumentservice.v1.SpotInstrumentService/GetInstrument"
	SpotInstrumentService_ListInstruments_FullMethodName   = "/spotinstrumentservice.v1.SpotInstrumentService/ListInstruments"
	SpotInstrumentService_ArchiveInstrument_FullMethodName = "/spotinstrumentservice.v1.SpotInstrumentService/ArchiveInstrument"
	SpotInstrumentService_UpdateRate_FullMethodName        = "/spotinstrumentservice.v1.SpotInstrumentService/UpdateRate"
)

// SpotInstrumentServiceClient is the client API for SpotInstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpotInstrumentService manages the catalog of tradable instruments (spot
// pairs) and their current exchange rates.
//
// Read methods (GetInstrument, ListInstruments) are public and require no
// authentication. Write methods (CreateInstrument, ArchiveInstrument,
// UpdateRate) require the caller to hold ROLE_ADMIN, verified against
// UserService.ValidateToken since this service does not issue or own
// tokens itself.
type SpotInstrumentServiceClient interface {
	// CreateInstrument registers a new tradable pair. The instrument starts
	// in INSTRUMENT_STATUS_ACTIVE with an initial rate of "0" until the first
	// UpdateRate call. Requires ROLE_ADMIN.
	CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error)
	// GetInstrument returns a single instrument by ID. Public, no auth
	// required.
	GetInstrument(ctx context.Context, in *GetInstrumentRequest, opts ...grpc.CallOption) (*GetInstrumentResponse, error)
	// ListInstruments returns all instruments, optionally filtered by status.
	// Public, no auth required. Not paginated.
	ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error)
	// ArchiveInstrument moves an instrument to INSTRUMENT_STATUS_DELISTED.
	// This is a soft delete: the row is preserved for referential integrity
	// with existing orders. Requires ROLE_ADMIN.
	ArchiveInstrument(ctx context.Context, in *ArchiveInstrumentRequest, opts ...grpc.CallOption) (*ArchiveInstrumentResponse, error)
	// UpdateRate sets the current exchange rate for an instrument. Expected
	// to be called frequently, potentially by an automated rate-feed actor
	// rather than a human. Requires ROLE_ADMIN.
	UpdateRate(ctx context.Context, in *UpdateRateRequest, opts ...grpc.CallOption) (*UpdateRateResponse, error)
}

type spotInstrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpotInstrumentServiceClient(cc grpc.ClientConnInterface) SpotInstrumentServiceClient {
	return &spotInstrumentServiceClient{cc}
}

func (c *spotInstrumentServiceClient) CreateInstrument(ctx context.Context, in *CreateInstrumentRequest, opts ...grpc.CallOption) (*CreateInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstrumentResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_CreateInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotInstrumentServiceClient) GetInstrument(ctx context.Context, in *GetInstrumentRequest, opts ...grpc.CallOption) (*GetInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstrumentResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_GetInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotInstrumentServiceClient) ListInstruments(ctx context.Context, in *ListInstrumentsRequest, opts ...grpc.CallOption) (*ListInstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstrumentsResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_ListInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotInstrumentServiceClient) ArchiveInstrument(ctx context.Context, in *ArchiveInstrumentRequest, opts ...grpc.CallOption) (*ArchiveInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveInstrumentResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_ArchiveInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spotInstrumentServiceClient) UpdateRate(ctx context.Context, in *UpdateRateRequest, opts ...grpc.CallOption) (*UpdateRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRateResponse)
	err := c.cc.Invoke(ctx, SpotInstrumentService_UpdateRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpotInstrumentServiceServer is the server API for SpotInstrumentService service.
// All implementations must embed UnimplementedSpotInstrumentServiceServer
// for forward compatibility.
//
// SpotInstrumentService manages the catalog of tradable instruments (spot
// pairs) and their current exchange rates.
//
// Read methods (GetInstrument, ListInstruments) are public and require no
// authentication. Write methods (CreateInstrument, ArchiveInstrument,
// UpdateRate) require the caller to hold ROLE_ADMIN, verified against
// UserService.ValidateToken since this service does not issue or own
// tokens itself.
type SpotInstrumentServiceServer interface {
	// CreateInstrument registers a new tradable pair. The instrument starts
	// in INSTRUMENT_STATUS_ACTIVE with an initial rate of "0" until the first
	// UpdateRate call. Requires ROLE_ADMIN.
	CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error)
	// GetInstrument returns a single instrument by ID. Public, no auth
	// required.
	GetInstrument(context.Context, *GetInstrumentRequest) (*GetInstrumentResponse, error)
	// ListInstruments returns all instruments, optionally filtered by status.
	// Public, no auth required. Not paginated.
	ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error)
	// ArchiveInstrument moves an instrument to INSTRUMENT_STATUS_DELISTED.
	// This is a soft delete: the row is preserved for referential integrity
	// with existing orders. Requires ROLE_ADMIN.
	ArchiveInstrument(context.Context, *ArchiveInstrumentRequest) (*ArchiveInstrumentResponse, error)
	// UpdateRate sets the current exchange rate for an instrument. Expected
	// to be called frequently, potentially by an automated rate-feed actor
	// rather than a human. Requires ROLE_ADMIN.
	UpdateRate(context.Context, *UpdateRateRequest) (*UpdateRateResponse, error)
	mustEmbedUnimplementedSpotInstrumentServiceServer()
}

// UnimplementedSpotInstrumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpotInstrumentServiceServer struct{}

func (UnimplementedSpotInstrumentServiceServer) CreateInstrument(context.Context, *CreateInstrumentRequest) (*CreateInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstrument not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) GetInstrument(context.Context, *GetInstrumentRequest) (*GetInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstrument not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) ListInstruments(context.Context, *ListInstrumentsRequest) (*ListInstrumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstruments not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) ArchiveInstrument(context.Context, *ArchiveInstrumentRequest) (*ArchiveInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveInstrument not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) UpdateRate(context.Context, *UpdateRateRequest) (*UpdateRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRate not implemented")
}
func (UnimplementedSpotInstrumentServiceServer) mustEmbedUnimplementedSpotInstrumentServiceServer() {}
func (UnimplementedSpotInstrumentServiceServer) testEmbeddedByValue()                               {}

// UnsafeSpotInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpotInstrumentServiceServer will
// result in compilation errors.
type UnsafeSpotInstrumentServiceServer interface {
	mustEmbedUnimplementedSpotInstrumentServiceServer()
}

func RegisterSpotInstrumentServiceServer(s grpc.ServiceRegistrar, srv SpotInstrumentServiceServer) {
	// If the following call panics, it indicates UnimplementedSpotInstrumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpotInstrumentService_ServiceDesc, srv)
}

func _SpotInstrumentService_CreateInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).CreateInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_CreateInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).CreateInstrument(ctx, req.(*CreateInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotInstrumentService_GetInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).GetInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_GetInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).GetInstrument(ctx, req.(*GetInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotInstrumentService_ListInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).ListInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_ListInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).ListInstruments(ctx, req.(*ListInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotInstrumentService_ArchiveInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).ArchiveInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_ArchiveInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).ArchiveInstrument(ctx, req.(*ArchiveInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpotInstrumentService_UpdateRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpotInstrumentServiceServer).UpdateRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpotInstrumentService_UpdateRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpotInstrumentServiceServer).UpdateRate(ctx, req.(*UpdateRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpotInstrumentService_ServiceDesc is the grpc.ServiceDesc for SpotInstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpotInstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "spotinstrumentservice.v1.SpotInstrumentService",
	HandlerType: (*SpotInstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstrument",
			Handler:    _SpotInstrumentService_CreateInstrument_Handler,
		},
		{
			MethodName: "GetInstrument",
			Handler:    _SpotInstrumentService_GetInstrument_Handler,
		},
		{
			MethodName: "ListInstruments",
			Handler:    _SpotInstrumentService_ListInstruments_Handler,
		},
		{
			MethodName: "ArchiveInstrument",
			Handler:    _SpotInstrumentService_ArchiveInstrument_Handler,
		},
		{
			MethodName: "UpdateRate",
			Handler:    _SpotInstrumentService_UpdateRate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "spotinstrumentservice/v1/spot_instrument.proto",
}
