// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orderservice/v1/order.proto

// Package orderservice.v1 defines the public gRPC contract for
// OrderService: placing, viewing and cancelling orders, and reading back
// the trades a matching engine produces when orders cross.

package orderv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide is the direction of an order.
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{0}
}

// OrderType determines whether price is required and whether the order
// rests in the book when it isn't fully filled immediately.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	// ORDER_TYPE_MARKET orders carry no price and execute against whatever
	// price is available right now; any unfilled remainder is cancelled,
	// never left resting.
	OrderType_ORDER_TYPE_MARKET OrderType = 1
	// ORDER_TYPE_LIMIT orders require an explicit price and rest in the
	// book until fully filled or cancelled.
	OrderType_ORDER_TYPE_LIMIT OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{1}
}

// OrderStatus reflects the current lifecycle state of an order.
// ORDER_STATUS_FILLED and ORDER_STATUS_CANCELLED are terminal: an order
// in either state can never change again.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED      OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN             OrderStatus = 1
	OrderStatus_ORDER_STATUS_CANCELLED        OrderStatus = 2
	OrderStatus_ORDER_STATUS_PARTIALLY_FILLED OrderStatus = 3
	OrderStatus_ORDER_STATUS_FILLED           OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_OPEN",
		2: "ORDER_STATUS_CANCELLED",
		3: "ORDER_STATUS_PARTIALLY_FILLED",
		4: "ORDER_STATUS_FILLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED":      0,
		"ORDER_STATUS_OPEN":             1,
		"ORDER_STATUS_CANCELLED":        2,
		"ORDER_STATUS_PARTIALLY_FILLED": 3,
		"ORDER_STATUS_FILLED":           4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{2}
}

// Order represents a single order placed by a user.
//
// price and quantity are decimal strings, not double, for the same reason
// as SpotInstrumentService.Instrument's monetary fields: to avoid
// floating-point rounding on values that represent real money.
type Order struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstrumentId string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=orderservice.v1.OrderSide" json:"side,omitempty"`
	Type         OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=orderservice.v1.OrderType" json:"type,omitempty"`
	// price is empty for market orders.
	Price string `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	// quantity is the original amount requested.
	Quantity  string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status    OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=orderservice.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// remaining_quantity is what's left unfilled. Equal to quantity when
	// the order was never matched at all; decreases as trades execute
	// against it; zero once ORDER_STATUS_FILLED.
	RemainingQuantity string `protobuf:"bytes,11,opt,name=remaining_quantity,json=remainingQuantity,proto3" json:"remaining_quantity,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orderservice_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetRemainingQuantity() string {
	if x != nil {
		return x.RemainingQuantity
	}
	return ""
}

// Trade is a single execution produced when a buy and a sell order cross.
// price is always the resting (maker) order's price, not the incoming
// (taker) order's — standard exchange convention.
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentId  string                 `protobuf:"bytes,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	BuyOrderId    string                 `protobuf:"bytes,3,opt,name=buy_order_id,json=buyOrderId,proto3" json:"buy_order_id,omitempty"`
	SellOrderId   string                 `protobuf:"bytes,4,opt,name=sell_order_id,json=sellOrderId,proto3" json:"sell_order_id,omitempty"`
	Price         string                 `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_orderservice_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *Trade) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trade) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *Trade) GetBuyOrderId() string {
	if x != nil {
		return x.BuyOrderId
	}
	return ""
}

func (x *Trade) GetSellOrderId() string {
	if x != nil {
		return x.SellOrderId
	}
	return ""
}

func (x *Trade) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Trade) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Trade) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLastTradePricesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// instrument_ids is capped at 500 per call — if SpotInstrumentService
	// ever tracks more active instruments than that, it should split the
	// request into batches rather than this growing unbounded.
	InstrumentIds []string `protobuf:"bytes,1,rep,name=instrument_ids,json=instrumentIds,proto3" json:"instrument_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastTradePricesRequest) Reset() {
	*x = GetLastTradePricesRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastTradePricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastTradePricesRequest) ProtoMessage() {}

func (x *GetLastTradePricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastTradePricesRequest.ProtoReflect.Descriptor instead.
func (*GetLastTradePricesRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetLastTradePricesRequest) GetInstrumentIds() []string {
	if x != nil {
		return x.InstrumentIds
	}
	return nil
}

type LastTradePrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstrumentId  string                 `protobuf:"bytes,1,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	TradedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=traded_at,json=tradedAt,proto3" json:"traded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LastTradePrice) Reset() {
	*x = LastTradePrice{}
	mi := &file_orderservice_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastTradePrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastTradePrice) ProtoMessage() {}

func (x *LastTradePrice) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastTradePrice.ProtoReflect.Descriptor instead.
func (*LastTradePrice) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *LastTradePrice) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *LastTradePrice) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *LastTradePrice) GetTradedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TradedAt
	}
	return nil
}

type GetLastTradePricesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// prices omits any instrument_id from the request that has never
	// traded — not an error per-entry, just absent.
	Prices        []*LastTradePrice `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastTradePricesResponse) Reset() {
	*x = GetLastTradePricesResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastTradePricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastTradePricesResponse) ProtoMessage() {}

func (x *GetLastTradePricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastTradePricesResponse.ProtoReflect.Descriptor instead.
func (*GetLastTradePricesResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetLastTradePricesResponse) GetPrices() []*LastTradePrice {
	if x != nil {
		return x.Prices
	}
	return nil
}

type CreateOrderRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstrumentId string                 `protobuf:"bytes,1,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=orderservice.v1.OrderSide" json:"side,omitempty"`
	Type         OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=orderservice.v1.OrderType" json:"type,omitempty"`
	// price is required for ORDER_TYPE_LIMIT and must be omitted for
	// ORDER_TYPE_MARKET; enforced in the application layer.
	Price    *string `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Quantity string  `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// idempotency_key, if provided, must be a client-generated UUID unique
	// per caller. A retried CreateOrder call with the same key and the same
	// caller returns the order that was actually created the first time,
	// rather than creating a duplicate — safe to retry after a timeout or
	// dropped connection without risking placing the same order twice.
	// Optional: omit it and each call creates a new order unconditionally.
	IdempotencyKey *string `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateOrderRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateOrderRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status_filter restricts the result to orders with this status. Unset
	// returns orders of every status.
	StatusFilter *OrderStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=orderservice.v1.OrderStatus,oneof" json:"status_filter,omitempty"`
	// page_size is the maximum number of orders to return. Defaults to 20
	// if unset or zero; capped at 100.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// page_token, if present, continues a previous ListOrders call. Opaque:
	// callers must not construct or parse it themselves, only pass back
	// what a prior response returned in next_page_token.
	PageToken     string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *ListOrdersRequest) GetStatusFilter() OrderStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListOrdersResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Orders []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	// next_page_token is empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesRequest) Reset() {
	*x = ListTradesRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesRequest) ProtoMessage() {}

func (x *ListTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesRequest.ProtoReflect.Descriptor instead.
func (*ListTradesRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *ListTradesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTradesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTradesResponse) Reset() {
	*x = ListTradesResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTradesResponse) ProtoMessage() {}

func (x *ListTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTradesResponse.ProtoReflect.Descriptor instead.
func (*ListTradesResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *ListTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

func (x *ListTradesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type ListOrderTradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderTradesRequest) Reset() {
	*x = ListOrderTradesRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderTradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderTradesRequest) ProtoMessage() {}

func (x *ListOrderTradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderTradesRequest.ProtoReflect.Descriptor instead.
func (*ListOrderTradesRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{15}
}

func (x *ListOrderTradesRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ListOrderTradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trades        []*Trade               `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderTradesResponse) Reset() {
	*x = ListOrderTradesResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderTradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderTradesResponse) ProtoMessage() {}

func (x *ListOrderTradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderTradesResponse.ProtoReflect.Descriptor instead.
func (*ListOrderTradesResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{16}
}

func (x *ListOrderTradesResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

var File_orderservice_v1_order_proto protoreflect.FileDescriptor

const file_orderservice_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1borderservice/v1/order.proto\x12\x0forderservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xc2\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12.\n" +
	"\x04side\x18\x04 \x01(\x0e2\x1a.orderservice.v1.OrderSideR\x04side\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.orderservice.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.orderservice.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\x12remaining_quantity\x18\v \x01(\tR\x11remainingQuantity\"\xef\x01\n" +
	"\x05Trade\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\tR\finstrumentId\x12 \n" +
	"\fbuy_order_id\x18\x03 \x01(\tR\n" +
	"buyOrderId\x12\"\n" +
	"\rsell_order_id\x18\x04 \x01(\tR\vsellOrderId\x12\x14\n" +
	"\x05price\x18\x05 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\tR\bquantity\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"M\n" +
	"\x19GetLastTradePricesRequest\x120\n" +
	"\x0einstrument_ids\x18\x01 \x03(\tB\t\xbaH\x06\x92\x01\x03\x10\xf4\x03R\rinstrumentIds\"\x84\x01\n" +
	"\x0eLastTradePrice\x12#\n" +
	"\rinstrument_id\x18\x01 \x01(\tR\finstrumentId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x127\n" +
	"\ttraded_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\btradedAt\"U\n" +
	"\x1aGetLastTradePricesResponse\x127\n" +
	"\x06prices\x18\x01 \x03(\v2\x1f.orderservice.v1.LastTradePriceR\x06prices\"\xd6\x02\n" +
	"\x12CreateOrderRequest\x12-\n" +
	"\rinstrument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\finstrumentId\x128\n" +
	"\x04side\x18\x02 \x01(\x0e2\x1a.orderservice.v1.OrderSideB\b\xbaH\x05\x82\x01\x02 \x00R\x04side\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.orderservice.v1.OrderTypeB\b\xbaH\x05\x82\x01\x02 \x00R\x04type\x12\"\n" +
	"\x05price\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\x05price\x88\x01\x01\x12#\n" +
	"\bquantity\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bquantity\x126\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01H\x01R\x0eidempotencyKey\x88\x01\x01B\b\n" +
	"\x06_priceB\x12\n" +
	"\x10_idempotency_key\"C\n" +
	"\x13CreateOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order\"+\n" +
	"\x0fGetOrderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"@\n" +
	"\x10GetOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order\"\xb4\x01\n" +
	"\x11ListOrdersRequest\x12F\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x1c.orderservice.v1.OrderStatusH\x00R\fstatusFilter\x88\x01\x01\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageTokenB\x10\n" +
	"\x0e_status_filter\"l\n" +
	"\x12ListOrdersResponse\x12.\n" +
	"\x06orders\x18\x01 \x03(\v2\x16.orderservice.v1.OrderR\x06orders\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\".\n" +
	"\x12CancelOrderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"C\n" +
	"\x13CancelOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order\"Z\n" +
	"\x11ListTradesRequest\x12&\n" +
	"\tpage_size\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"l\n" +
	"\x12ListTradesResponse\x12.\n" +
	"\x06trades\x18\x01 \x03(\v2\x16.orderservice.v1.TradeR\x06trades\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"=\n" +
	"\x16ListOrderTradesRequest\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aorderId\"I\n" +
	"\x17ListOrderTradesResponse\x12.\n" +
	"\x06trades\x18\x01 \x03(\v2\x16.orderservice.v1.TradeR\x06trades*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02*\x9a\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x02\x12!\n" +
	"\x1dORDER_STATUS_PARTIALLY_FILLED\x10\x03\x12\x17\n" +
	"\x13ORDER_STATUS_FILLED\x10\x042\xa4\x05\n" +
	"\fOrderService\x12o\n" +
	"\x12GetLastTradePrices\x12*.orderservice.v1.GetLastTradePricesRequest\x1a+.orderservice.v1.GetLastTradePricesResponse\"\x00\x12Z\n" +
	"\vCreateOrder\x12#.orderservice.v1.CreateOrderRequest\x1a$.orderservice.v1.CreateOrderResponse\"\x00\x12Q\n" +
	"\bGetOrder\x12 .orderservice.v1.GetOrderRequest\x1a!.orderservice.v1.GetOrderResponse\"\x00\x12W\n" +
	"\n" +
	"ListOrders\x12\".orderservice.v1.ListOrdersRequest\x1a#.orderservice.v1.ListOrdersResponse\"\x00\x12Z\n" +
	"\vCancelOrder\x12#.orderservice.v1.CancelOrderRequest\x1a$.orderservice.v1.CancelOrderResponse\"\x00\x12W\n" +
	"\n" +
	"ListTrades\x12\".orderservice.v1.ListTradesRequest\x1a#.orderservice.v1.ListTradesResponse\"\x00\x12f\n" +
	"\x0fListOrderTrades\x12'.orderservice.v1.ListOrderTradesRequest\x1a(.orderservice.v1.ListOrderTradesResponse\"\x00B\x19Z\x17orderservice/v1;orderv1b\x06proto3"

var (
	file_orderservice_v1_order_proto_rawDescOnce sync.Once
	file_orderservice_v1_order_proto_rawDescData []byte
)

func file_orderservice_v1_order_proto_rawDescGZIP() []byte {
	file_orderservice_v1_order_proto_rawDescOnce.Do(func() {
		file_orderservice_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderservice_v1_order_proto_rawDesc), len(file_orderservice_v1_order_proto_rawDesc)))
	})
	return file_orderservice_v1_order_proto_rawDescData
}

var file_orderservice_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orderservice_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_orderservice_v1_order_proto_goTypes = []any{
	(OrderSide)(0),                     // 0: orderservice.v1.OrderSide
	(OrderType)(0),                     // 1: orderservice.v1.OrderType
	(OrderStatus)(0),                   // 2: orderservice.v1.OrderStatus
	(*Order)(nil),                      // 3: orderservice.v1.Order
	(*Trade)(nil),                      // 4: orderservice.v1.Trade
	(*GetLastTradePricesRequest)(nil),  // 5: orderservice.v1.GetLastTradePricesRequest
	(*LastTradePrice)(nil),             // 6: orderservice.v1.LastTradePrice
	(*GetLastTradePricesResponse)(nil), // 7: orderservice.v1.GetLastTradePricesResponse
	(*CreateOrderRequest)(nil),         // 8: orderservice.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),        // 9: orderservice.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),            // 10: orderservice.v1.GetOrderRequest
	(*GetOrderResponse)(nil),           // 11: orderservice.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),          // 12: orderservice.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),         // 13: orderservice.v1.ListOrdersResponse
	(*CancelOrderRequest)(nil),         // 14: orderservice.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),        // 15: orderservice.v1.CancelOrderResponse
	(*ListTradesRequest)(nil),          // 16: orderservice.v1.ListTradesRequest
	(*ListTradesResponse)(nil),         // 17: orderservice.v1.ListTradesResponse
	(*ListOrderTradesRequest)(nil),     // 18: orderservice.v1.ListOrderTradesRequest
	(*ListOrderTradesResponse)(nil),    // 19: orderservice.v1.ListOrderTradesResponse
	(*timestamppb.Timestamp)(nil),      // 20: google.protobuf.Timestamp
}
var file_orderservice_v1_order_proto_depIdxs = []int32{
	0,  // 0: orderservice.v1.Order.side:type_name -> orderservice.v1.OrderSide
	1,  // 1: orderservice.v1.Order.type:type_name -> orderservice.v1.OrderType
	2,  // 2: orderservice.v1.Order.status:type_name -> orderservice.v1.OrderStatus
	20, // 3: orderservice.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	20, // 4: orderservice.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	20, // 5: orderservice.v1.Trade.created_at:type_name -> google.protobuf.Timestamp
	20, // 6: orderservice.v1.LastTradePrice.traded_at:type_name -> google.protobuf.Timestamp
	6,  // 7: orderservice.v1.GetLastTradePricesResponse.prices:type_name -> orderservice.v1.LastTradePrice
	0,  // 8: orderservice.v1.CreateOrderRequest.side:type_name -> orderservice.v1.OrderSide
	1,  // 9: orderservice.v1.CreateOrderRequest.type:type_name -> orderservice.v1.OrderType
	3,  // 10: orderservice.v1.CreateOrderResponse.order:type_name -> orderservice.v1.Order
	3,  // 11: orderservice.v1.GetOrderResponse.order:type_name -> orderservice.v1.Order
	2,  // 12: orderservice.v1.ListOrdersRequest.status_filter:type_name -> orderservice.v1.OrderStatus
	3,  // 13: orderservice.v1.ListOrdersResponse.orders:type_name -> orderservice.v1.Order
	3,  // 14: orderservice.v1.CancelOrderResponse.order:type_name -> orderservice.v1.Order
	4,  // 15: orderservice.v1.ListTradesResponse.trades:type_name -> orderservice.v1.Trade
	4,  // 16: orderservice.v1.ListOrderTradesResponse.trades:type_name -> orderservice.v1.Trade
	5,  // 17: orderservice.v1.OrderService.GetLastTradePrices:input_type -> orderservice.v1.GetLastTradePricesRequest
	8,  // 18: orderservice.v1.OrderService.CreateOrder:input_type -> orderservice.v1.CreateOrderRequest
	10, // 19: orderservice.v1.OrderService.GetOrder:input_type -> orderservice.v1.GetOrderRequest
	12, // 20: orderservice.v1.OrderService.ListOrders:input_type -> orderservice.v1.ListOrdersRequest
	14, // 21: orderservice.v1.OrderService.CancelOrder:input_type -> orderservice.v1.CancelOrderRequest
	16, // 22: orderservice.v1.OrderService.ListTrades:input_type -> orderservice.v1.ListTradesRequest
	18, // 23: orderservice.v1.OrderService.ListOrderTrades:input_type -> orderservice.v1.ListOrderTradesRequest
	7,  // 24: orderservice.v1.OrderService.GetLastTradePrices:output_type -> orderservice.v1.GetLastTradePricesResponse
	9,  // 25: orderservice.v1.OrderService.CreateOrder:output_type -> orderservice.v1.CreateOrderResponse
	11, // 26: orderservice.v1.OrderService.GetOrder:output_type -> orderservice.v1.GetOrderResponse
	13, // 27: orderservice.v1.OrderService.ListOrders:output_type -> orderservice.v1.ListOrdersResponse
	15, // 28: orderservice.v1.OrderService.CancelOrder:output_type -> orderservice.v1.CancelOrderResponse
	17, // 29: orderservice.v1.OrderService.ListTrades:output_type -> orderservice.v1.ListTradesResponse
	19, // 30: orderservice.v1.OrderService.ListOrderTrades:output_type -> orderservice.v1.ListOrderTradesResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_orderservice_v1_order_proto_init() }
func file_orderservice_v1_order_proto_init() {
	if File_orderservice_v1_order_proto != nil {
		return
	}
	file_orderservice_v1_order_proto_msgTypes[5].OneofWrappers = []any{}
	file_orderservice_v1_order_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderservice_v1_order_proto_rawDesc), len(file_orderservice_v1_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderservice_v1_order_proto_goTypes,
		DependencyIndexes: file_orderservice_v1_order_proto_depIdxs,
		EnumInfos:         file_orderservice_v1_order_proto_enumTypes,
		MessageInfos:      file_orderservice_v1_order_proto_msgTypes,
	}.Build()
	File_orderservice_v1_order_proto = out.File
	file_orderservice_v1_order_proto_goTypes = nil
	file_orderservice_v1_order_proto_depIdxs = nil
}
