// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orderservice/v1/order.proto

// Package orderservice.v1 defines the public gRPC contract for
// OrderService: placing, viewing and cancelling orders. This first version
// has no matching engine — orders are recorded and can be cancelled, but
// are never automatically filled against each other.

package orderv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderSide is the direction of an order.
type OrderSide int32

const (
	OrderSide_ORDER_SIDE_UNSPECIFIED OrderSide = 0
	OrderSide_ORDER_SIDE_BUY         OrderSide = 1
	OrderSide_ORDER_SIDE_SELL        OrderSide = 2
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "ORDER_SIDE_UNSPECIFIED",
		1: "ORDER_SIDE_BUY",
		2: "ORDER_SIDE_SELL",
	}
	OrderSide_value = map[string]int32{
		"ORDER_SIDE_UNSPECIFIED": 0,
		"ORDER_SIDE_BUY":         1,
		"ORDER_SIDE_SELL":        2,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[0]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{0}
}

// OrderType determines whether price is required.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	// ORDER_TYPE_MARKET orders carry no price: they are intended to execute
	// at the prevailing market rate once a matching engine exists. price
	// must not be set on a market order.
	OrderType_ORDER_TYPE_MARKET OrderType = 1
	// ORDER_TYPE_LIMIT orders require an explicit price.
	OrderType_ORDER_TYPE_LIMIT OrderType = 2
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "ORDER_TYPE_UNSPECIFIED",
		1: "ORDER_TYPE_MARKET",
		2: "ORDER_TYPE_LIMIT",
	}
	OrderType_value = map[string]int32{
		"ORDER_TYPE_UNSPECIFIED": 0,
		"ORDER_TYPE_MARKET":      1,
		"ORDER_TYPE_LIMIT":       2,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[1].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[1]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{1}
}

// OrderStatus reflects the current lifecycle state of an order. There is
// no "filled" status yet: without a matching engine, an order only ever
// transitions from open to cancelled.
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_OPEN        OrderStatus = 1
	OrderStatus_ORDER_STATUS_CANCELLED   OrderStatus = 2
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_OPEN",
		2: "ORDER_STATUS_CANCELLED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_OPEN":        1,
		"ORDER_STATUS_CANCELLED":   2,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_orderservice_v1_order_proto_enumTypes[2].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_orderservice_v1_order_proto_enumTypes[2]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{2}
}

// Order represents a single order placed by a user.
//
// price and quantity are decimal strings, not double, for the same reason
// as SpotInstrumentService.Instrument's monetary fields: to avoid
// floating-point rounding on values that represent real money.
type Order struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InstrumentId string                 `protobuf:"bytes,3,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=orderservice.v1.OrderSide" json:"side,omitempty"`
	Type         OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=orderservice.v1.OrderType" json:"type,omitempty"`
	// price is empty for market orders.
	Price         string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      string                 `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        OrderStatus            `protobuf:"varint,8,opt,name=status,proto3,enum=orderservice.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orderservice_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateOrderRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InstrumentId string                 `protobuf:"bytes,1,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	Side         OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=orderservice.v1.OrderSide" json:"side,omitempty"`
	Type         OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=orderservice.v1.OrderType" json:"type,omitempty"`
	// price is required for ORDER_TYPE_LIMIT and must be omitted for
	// ORDER_TYPE_MARKET; enforced in the application layer.
	Price         *string `protobuf:"bytes,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Quantity      string  `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderRequest) GetInstrumentId() string {
	if x != nil {
		return x.InstrumentId
	}
	return ""
}

func (x *CreateOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *CreateOrderRequest) GetPrice() string {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return ""
}

func (x *CreateOrderRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status_filter restricts the result to orders with this status. Unset
	// returns orders of every status.
	StatusFilter  *OrderStatus `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=orderservice.v1.OrderStatus,oneof" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersRequest) GetStatusFilter() OrderStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_orderservice_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_orderservice_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orderservice_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_orderservice_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *CancelOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_orderservice_v1_order_proto protoreflect.FileDescriptor

const file_orderservice_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1borderservice/v1/order.proto\x12\x0forderservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x93\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rinstrument_id\x18\x03 \x01(\tR\finstrumentId\x12.\n" +
	"\x04side\x18\x04 \x01(\x0e2\x1a.orderservice.v1.OrderSideR\x04side\x12.\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1a.orderservice.v1.OrderTypeR\x04type\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\bquantity\x18\a \x01(\tR\bquantity\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.orderservice.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8a\x02\n" +
	"\x12CreateOrderRequest\x12-\n" +
	"\rinstrument_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\finstrumentId\x128\n" +
	"\x04side\x18\x02 \x01(\x0e2\x1a.orderservice.v1.OrderSideB\b\xbaH\x05\x82\x01\x02 \x00R\x04side\x128\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.orderservice.v1.OrderTypeB\b\xbaH\x05\x82\x01\x02 \x00R\x04type\x12\"\n" +
	"\x05price\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\x05price\x88\x01\x01\x12#\n" +
	"\bquantity\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bquantityB\b\n" +
	"\x06_price\"C\n" +
	"\x13CreateOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order\"+\n" +
	"\x0fGetOrderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"@\n" +
	"\x10GetOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order\"m\n" +
	"\x11ListOrdersRequest\x12F\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x1c.orderservice.v1.OrderStatusH\x00R\fstatusFilter\x88\x01\x01B\x10\n" +
	"\x0e_status_filter\"D\n" +
	"\x12ListOrdersResponse\x12.\n" +
	"\x06orders\x18\x01 \x03(\v2\x16.orderservice.v1.OrderR\x06orders\".\n" +
	"\x12CancelOrderRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"C\n" +
	"\x13CancelOrderResponse\x12,\n" +
	"\x05order\x18\x01 \x01(\v2\x16.orderservice.v1.OrderR\x05order*P\n" +
	"\tOrderSide\x12\x1a\n" +
	"\x16ORDER_SIDE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eORDER_SIDE_BUY\x10\x01\x12\x13\n" +
	"\x0fORDER_SIDE_SELL\x10\x02*T\n" +
	"\tOrderType\x12\x1a\n" +
	"\x16ORDER_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_TYPE_MARKET\x10\x01\x12\x14\n" +
	"\x10ORDER_TYPE_LIMIT\x10\x02*^\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ORDER_STATUS_OPEN\x10\x01\x12\x1a\n" +
	"\x16ORDER_STATUS_CANCELLED\x10\x022\xf2\x02\n" +
	"\fOrderService\x12Z\n" +
	"\vCreateOrder\x12#.orderservice.v1.CreateOrderRequest\x1a$.orderservice.v1.CreateOrderResponse\"\x00\x12Q\n" +
	"\bGetOrder\x12 .orderservice.v1.GetOrderRequest\x1a!.orderservice.v1.GetOrderResponse\"\x00\x12W\n" +
	"\n" +
	"ListOrders\x12\".orderservice.v1.ListOrdersRequest\x1a#.orderservice.v1.ListOrdersResponse\"\x00\x12Z\n" +
	"\vCancelOrder\x12#.orderservice.v1.CancelOrderRequest\x1a$.orderservice.v1.CancelOrderResponse\"\x00B\x19Z\x17orderservice/v1;orderv1b\x06proto3"

var (
	file_orderservice_v1_order_proto_rawDescOnce sync.Once
	file_orderservice_v1_order_proto_rawDescData []byte
)

func file_orderservice_v1_order_proto_rawDescGZIP() []byte {
	file_orderservice_v1_order_proto_rawDescOnce.Do(func() {
		file_orderservice_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderservice_v1_order_proto_rawDesc), len(file_orderservice_v1_order_proto_rawDesc)))
	})
	return file_orderservice_v1_order_proto_rawDescData
}

var file_orderservice_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_orderservice_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orderservice_v1_order_proto_goTypes = []any{
	(OrderSide)(0),                // 0: orderservice.v1.OrderSide
	(OrderType)(0),                // 1: orderservice.v1.OrderType
	(OrderStatus)(0),              // 2: orderservice.v1.OrderStatus
	(*Order)(nil),                 // 3: orderservice.v1.Order
	(*CreateOrderRequest)(nil),    // 4: orderservice.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),   // 5: orderservice.v1.CreateOrderResponse
	(*GetOrderRequest)(nil),       // 6: orderservice.v1.GetOrderRequest
	(*GetOrderResponse)(nil),      // 7: orderservice.v1.GetOrderResponse
	(*ListOrdersRequest)(nil),     // 8: orderservice.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),    // 9: orderservice.v1.ListOrdersResponse
	(*CancelOrderRequest)(nil),    // 10: orderservice.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),   // 11: orderservice.v1.CancelOrderResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_orderservice_v1_order_proto_depIdxs = []int32{
	0,  // 0: orderservice.v1.Order.side:type_name -> orderservice.v1.OrderSide
	1,  // 1: orderservice.v1.Order.type:type_name -> orderservice.v1.OrderType
	2,  // 2: orderservice.v1.Order.status:type_name -> orderservice.v1.OrderStatus
	12, // 3: orderservice.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: orderservice.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: orderservice.v1.CreateOrderRequest.side:type_name -> orderservice.v1.OrderSide
	1,  // 6: orderservice.v1.CreateOrderRequest.type:type_name -> orderservice.v1.OrderType
	3,  // 7: orderservice.v1.CreateOrderResponse.order:type_name -> orderservice.v1.Order
	3,  // 8: orderservice.v1.GetOrderResponse.order:type_name -> orderservice.v1.Order
	2,  // 9: orderservice.v1.ListOrdersRequest.status_filter:type_name -> orderservice.v1.OrderStatus
	3,  // 10: orderservice.v1.ListOrdersResponse.orders:type_name -> orderservice.v1.Order
	3,  // 11: orderservice.v1.CancelOrderResponse.order:type_name -> orderservice.v1.Order
	4,  // 12: orderservice.v1.OrderService.CreateOrder:input_type -> orderservice.v1.CreateOrderRequest
	6,  // 13: orderservice.v1.OrderService.GetOrder:input_type -> orderservice.v1.GetOrderRequest
	8,  // 14: orderservice.v1.OrderService.ListOrders:input_type -> orderservice.v1.ListOrdersRequest
	10, // 15: orderservice.v1.OrderService.CancelOrder:input_type -> orderservice.v1.CancelOrderRequest
	5,  // 16: orderservice.v1.OrderService.CreateOrder:output_type -> orderservice.v1.CreateOrderResponse
	7,  // 17: orderservice.v1.OrderService.GetOrder:output_type -> orderservice.v1.GetOrderResponse
	9,  // 18: orderservice.v1.OrderService.ListOrders:output_type -> orderservice.v1.ListOrdersResponse
	11, // 19: orderservice.v1.OrderService.CancelOrder:output_type -> orderservice.v1.CancelOrderResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_orderservice_v1_order_proto_init() }
func file_orderservice_v1_order_proto_init() {
	if File_orderservice_v1_order_proto != nil {
		return
	}
	file_orderservice_v1_order_proto_msgTypes[1].OneofWrappers = []any{}
	file_orderservice_v1_order_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderservice_v1_order_proto_rawDesc), len(file_orderservice_v1_order_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orderservice_v1_order_proto_goTypes,
		DependencyIndexes: file_orderservice_v1_order_proto_depIdxs,
		EnumInfos:         file_orderservice_v1_order_proto_enumTypes,
		MessageInfos:      file_orderservice_v1_order_proto_msgTypes,
	}.Build()
	File_orderservice_v1_order_proto = out.File
	file_orderservice_v1_order_proto_goTypes = nil
	file_orderservice_v1_order_proto_depIdxs = nil
}
