// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: walletservice/wallet.proto

// Package walletservice.v1 defines the public gRPC contract for
// WalletService: user balances and the reserve/settle primitives that back
// order placement and trade execution.
//
// This contract is defined ahead of the implementation, as a dependency
// that OrderService's future matching engine will call into. See the
// per-RPC comments below for the open design question this raises around
// service-to-service authentication.

package walletv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Balance is a user's holdings of a single asset, split into funds free
// to use (available) and funds locked under open orders (reserved).
// Both fields are decimal strings, not double, for the same reason as
// every other monetary field in this system: to avoid floating-point
// rounding on values that represent real money.
type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Available     string                 `protobuf:"bytes,3,opt,name=available,proto3" json:"available,omitempty"`
	Reserved      string                 `protobuf:"bytes,4,opt,name=reserved,proto3" json:"reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_walletservice_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Balance) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Balance) GetAvailable() string {
	if x != nil {
		return x.Available
	}
	return ""
}

func (x *Balance) GetReserved() string {
	if x != nil {
		return x.Reserved
	}
	return ""
}

// Reservation represents funds locked by a single Reserve call. Returned
// so the caller (OrderService) can later reference it in
// ReleaseReservation/SettleReservation without needing to reconstruct
// which wallet call backed a given order.
type Reservation struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset  string                 `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	// reference_id ties this reservation back to the order that caused it,
	// for auditability. Opaque to WalletService itself.
	ReferenceId   string `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_walletservice_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *Reservation) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Reservation) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *GetBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBalanceResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ListBalancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesRequest) Reset() {
	*x = ListBalancesRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesRequest) ProtoMessage() {}

func (x *ListBalancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesRequest.ProtoReflect.Descriptor instead.
func (*ListBalancesRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{4}
}

type ListBalancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balances      []*Balance             `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBalancesResponse) Reset() {
	*x = ListBalancesResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBalancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBalancesResponse) ProtoMessage() {}

func (x *ListBalancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBalancesResponse.ProtoReflect.Descriptor instead.
func (*ListBalancesResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *ListBalancesResponse) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

type DepositRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositRequest) Reset() {
	*x = DepositRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositRequest) ProtoMessage() {}

func (x *DepositRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositRequest.ProtoReflect.Descriptor instead.
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *DepositRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DepositRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *DepositRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type DepositResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepositResponse) Reset() {
	*x = DepositResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepositResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositResponse) ProtoMessage() {}

func (x *DepositResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositResponse.ProtoReflect.Descriptor instead.
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *DepositResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *ReserveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *ReserveRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ReserveRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{9}
}

func (x *ReserveResponse) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type ReleaseReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationRequest) Reset() {
	*x = ReleaseReservationRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationRequest) ProtoMessage() {}

func (x *ReleaseReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationRequest.ProtoReflect.Descriptor instead.
func (*ReleaseReservationRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{10}
}

func (x *ReleaseReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type ReleaseReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReservationResponse) Reset() {
	*x = ReleaseReservationResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReservationResponse) ProtoMessage() {}

func (x *ReleaseReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReservationResponse.ProtoReflect.Descriptor instead.
func (*ReleaseReservationResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseReservationResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type SettleReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleReservationRequest) Reset() {
	*x = SettleReservationRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleReservationRequest) ProtoMessage() {}

func (x *SettleReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleReservationRequest.ProtoReflect.Descriptor instead.
func (*SettleReservationRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{12}
}

func (x *SettleReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *SettleReservationRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type SettleReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettleReservationResponse) Reset() {
	*x = SettleReservationResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleReservationResponse) ProtoMessage() {}

func (x *SettleReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleReservationResponse.ProtoReflect.Descriptor instead.
func (*SettleReservationResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{13}
}

func (x *SettleReservationResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

type CreditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Asset         string                 `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,4,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	mi := &file_walletservice_wallet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{14}
}

func (x *CreditRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreditRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *CreditRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreditRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

type CreditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *Balance               `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditResponse) Reset() {
	*x = CreditResponse{}
	mi := &file_walletservice_wallet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditResponse) ProtoMessage() {}

func (x *CreditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_walletservice_wallet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditResponse.ProtoReflect.Descriptor instead.
func (*CreditResponse) Descriptor() ([]byte, []int) {
	return file_walletservice_wallet_proto_rawDescGZIP(), []int{15}
}

func (x *CreditResponse) GetBalance() *Balance {
	if x != nil {
		return x.Balance
	}
	return nil
}

var File_walletservice_wallet_proto protoreflect.FileDescriptor

const file_walletservice_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1awalletservice/wallet.proto\x12\x10walletservice.v1\x1a\x1bbuf/validate/validate.proto\"r\n" +
	"\aBalance\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05asset\x18\x02 \x01(\tR\x05asset\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\tR\tavailable\x12\x1a\n" +
	"\breserved\x18\x04 \x01(\tR\breserved\"\x87\x01\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05asset\x18\x03 \x01(\tR\x05asset\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\"2\n" +
	"\x11GetBalanceRequest\x12\x1d\n" +
	"\x05asset\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05asset\"I\n" +
	"\x12GetBalanceResponse\x123\n" +
	"\abalance\x18\x01 \x01(\v2\x19.walletservice.v1.BalanceR\abalance\"\x15\n" +
	"\x13ListBalancesRequest\"M\n" +
	"\x14ListBalancesResponse\x125\n" +
	"\bbalances\x18\x01 \x03(\v2\x19.walletservice.v1.BalanceR\bbalances\"s\n" +
	"\x0eDepositRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05asset\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05asset\x12\x1f\n" +
	"\x06amount\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\"F\n" +
	"\x0fDepositResponse\x123\n" +
	"\abalance\x18\x01 \x01(\v2\x19.walletservice.v1.BalanceR\abalance\"\x9f\x01\n" +
	"\x0eReserveRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05asset\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05asset\x12\x1f\n" +
	"\x06amount\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\x12*\n" +
	"\freference_id\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vreferenceId\"R\n" +
	"\x0fReserveResponse\x12?\n" +
	"\vreservation\x18\x01 \x01(\v2\x1d.walletservice.v1.ReservationR\vreservation\"L\n" +
	"\x19ReleaseReservationRequest\x12/\n" +
	"\x0ereservation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rreservationId\"Q\n" +
	"\x1aReleaseReservationResponse\x123\n" +
	"\abalance\x18\x01 \x01(\v2\x19.walletservice.v1.BalanceR\abalance\"l\n" +
	"\x18SettleReservationRequest\x12/\n" +
	"\x0ereservation_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\rreservationId\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\"P\n" +
	"\x19SettleReservationResponse\x123\n" +
	"\abalance\x18\x01 \x01(\v2\x19.walletservice.v1.BalanceR\abalance\"\x9e\x01\n" +
	"\rCreditRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\x12\x1d\n" +
	"\x05asset\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05asset\x12\x1f\n" +
	"\x06amount\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06amount\x12*\n" +
	"\freference_id\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vreferenceId\"E\n" +
	"\x0eCreditResponse\x123\n" +
	"\abalance\x18\x01 \x01(\v2\x19.walletservice.v1.BalanceR\abalance2\xa1\x05\n" +
	"\rWalletService\x12Y\n" +
	"\n" +
	"GetBalance\x12#.walletservice.v1.GetBalanceRequest\x1a$.walletservice.v1.GetBalanceResponse\"\x00\x12_\n" +
	"\fListBalances\x12%.walletservice.v1.ListBalancesRequest\x1a&.walletservice.v1.ListBalancesResponse\"\x00\x12P\n" +
	"\aDeposit\x12 .walletservice.v1.DepositRequest\x1a!.walletservice.v1.DepositResponse\"\x00\x12P\n" +
	"\aReserve\x12 .walletservice.v1.ReserveRequest\x1a!.walletservice.v1.ReserveResponse\"\x00\x12q\n" +
	"\x12ReleaseReservation\x12+.walletservice.v1.ReleaseReservationRequest\x1a,.walletservice.v1.ReleaseReservationResponse\"\x00\x12n\n" +
	"\x11SettleReservation\x12*.walletservice.v1.SettleReservationRequest\x1a+.walletservice.v1.SettleReservationResponse\"\x00\x12M\n" +
	"\x06Credit\x12\x1f.walletservice.v1.CreditRequest\x1a .walletservice.v1.CreditResponse\"\x00B\x1bZ\x19walletservice/v1;walletv1b\x06proto3"

var (
	file_walletservice_wallet_proto_rawDescOnce sync.Once
	file_walletservice_wallet_proto_rawDescData []byte
)

func file_walletservice_wallet_proto_rawDescGZIP() []byte {
	file_walletservice_wallet_proto_rawDescOnce.Do(func() {
		file_walletservice_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_walletservice_wallet_proto_rawDesc), len(file_walletservice_wallet_proto_rawDesc)))
	})
	return file_walletservice_wallet_proto_rawDescData
}

var file_walletservice_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_walletservice_wallet_proto_goTypes = []any{
	(*Balance)(nil),                    // 0: walletservice.v1.Balance
	(*Reservation)(nil),                // 1: walletservice.v1.Reservation
	(*GetBalanceRequest)(nil),          // 2: walletservice.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),         // 3: walletservice.v1.GetBalanceResponse
	(*ListBalancesRequest)(nil),        // 4: walletservice.v1.ListBalancesRequest
	(*ListBalancesResponse)(nil),       // 5: walletservice.v1.ListBalancesResponse
	(*DepositRequest)(nil),             // 6: walletservice.v1.DepositRequest
	(*DepositResponse)(nil),            // 7: walletservice.v1.DepositResponse
	(*ReserveRequest)(nil),             // 8: walletservice.v1.ReserveRequest
	(*ReserveResponse)(nil),            // 9: walletservice.v1.ReserveResponse
	(*ReleaseReservationRequest)(nil),  // 10: walletservice.v1.ReleaseReservationRequest
	(*ReleaseReservationResponse)(nil), // 11: walletservice.v1.ReleaseReservationResponse
	(*SettleReservationRequest)(nil),   // 12: walletservice.v1.SettleReservationRequest
	(*SettleReservationResponse)(nil),  // 13: walletservice.v1.SettleReservationResponse
	(*CreditRequest)(nil),              // 14: walletservice.v1.CreditRequest
	(*CreditResponse)(nil),             // 15: walletservice.v1.CreditResponse
}
var file_walletservice_wallet_proto_depIdxs = []int32{
	0,  // 0: walletservice.v1.GetBalanceResponse.balance:type_name -> walletservice.v1.Balance
	0,  // 1: walletservice.v1.ListBalancesResponse.balances:type_name -> walletservice.v1.Balance
	0,  // 2: walletservice.v1.DepositResponse.balance:type_name -> walletservice.v1.Balance
	1,  // 3: walletservice.v1.ReserveResponse.reservation:type_name -> walletservice.v1.Reservation
	0,  // 4: walletservice.v1.ReleaseReservationResponse.balance:type_name -> walletservice.v1.Balance
	0,  // 5: walletservice.v1.SettleReservationResponse.balance:type_name -> walletservice.v1.Balance
	0,  // 6: walletservice.v1.CreditResponse.balance:type_name -> walletservice.v1.Balance
	2,  // 7: walletservice.v1.WalletService.GetBalance:input_type -> walletservice.v1.GetBalanceRequest
	4,  // 8: walletservice.v1.WalletService.ListBalances:input_type -> walletservice.v1.ListBalancesRequest
	6,  // 9: walletservice.v1.WalletService.Deposit:input_type -> walletservice.v1.DepositRequest
	8,  // 10: walletservice.v1.WalletService.Reserve:input_type -> walletservice.v1.ReserveRequest
	10, // 11: walletservice.v1.WalletService.ReleaseReservation:input_type -> walletservice.v1.ReleaseReservationRequest
	12, // 12: walletservice.v1.WalletService.SettleReservation:input_type -> walletservice.v1.SettleReservationRequest
	14, // 13: walletservice.v1.WalletService.Credit:input_type -> walletservice.v1.CreditRequest
	3,  // 14: walletservice.v1.WalletService.GetBalance:output_type -> walletservice.v1.GetBalanceResponse
	5,  // 15: walletservice.v1.WalletService.ListBalances:output_type -> walletservice.v1.ListBalancesResponse
	7,  // 16: walletservice.v1.WalletService.Deposit:output_type -> walletservice.v1.DepositResponse
	9,  // 17: walletservice.v1.WalletService.Reserve:output_type -> walletservice.v1.ReserveResponse
	11, // 18: walletservice.v1.WalletService.ReleaseReservation:output_type -> walletservice.v1.ReleaseReservationResponse
	13, // 19: walletservice.v1.WalletService.SettleReservation:output_type -> walletservice.v1.SettleReservationResponse
	15, // 20: walletservice.v1.WalletService.Credit:output_type -> walletservice.v1.CreditResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_walletservice_wallet_proto_init() }
func file_walletservice_wallet_proto_init() {
	if File_walletservice_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_walletservice_wallet_proto_rawDesc), len(file_walletservice_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_walletservice_wallet_proto_goTypes,
		DependencyIndexes: file_walletservice_wallet_proto_depIdxs,
		MessageInfos:      file_walletservice_wallet_proto_msgTypes,
	}.Build()
	File_walletservice_wallet_proto = out.File
	file_walletservice_wallet_proto_goTypes = nil
	file_walletservice_wallet_proto_depIdxs = nil
}
