// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: walletservice/wallet.proto

// Package walletservice.v1 defines the public gRPC contract for
// WalletService: user balances and the reserve/settle primitives that back
// order placement and trade execution.
//
// This contract is defined ahead of the implementation, as a dependency
// that OrderService's future matching engine will call into. See the
// per-RPC comments below for the open design question this raises around
// service-to-service authentication.

package walletv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletService_GetBalance_FullMethodName         = "/walletservice.v1.WalletService/GetBalance"
	WalletService_ListBalances_FullMethodName       = "/walletservice.v1.WalletService/ListBalances"
	WalletService_Deposit_FullMethodName            = "/walletservice.v1.WalletService/Deposit"
	WalletService_Reserve_FullMethodName            = "/walletservice.v1.WalletService/Reserve"
	WalletService_ReleaseReservation_FullMethodName = "/walletservice.v1.WalletService/ReleaseReservation"
	WalletService_SettleReservation_FullMethodName  = "/walletservice.v1.WalletService/SettleReservation"
	WalletService_Credit_FullMethodName             = "/walletservice.v1.WalletService/Credit"
)

// WalletServiceClient is the client API for WalletService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WalletService manages per-user, per-asset balances.
//
// GetBalance/ListBalances/Deposit are called with a normal user access
// token, validated against UserService.ValidateToken exactly like
// SpotInstrumentService/OrderService already do.
//
// Reserve/ReleaseReservation/SettleReservation/Credit are different: they
// are not actions a user takes directly, but internal calls OrderService
// (and, later, its matching engine) makes on a user's behalf while
// processing an order or executing a trade — including at match time,
// which happens asynchronously, outside the lifetime of any single user
// request. Forwarding the original user's access token does not fit this
// pattern. These four RPCs will need a service-to-service credential
// (e.g. a machine account / mTLS) distinct from user JWTs — deliberately
// left as an open question until the calling side (OrderService's
// matching engine) is implemented, rather than guessed at here.
type WalletServiceClient interface {
	// GetBalance returns the caller's own balance for a single asset. A
	// balance that has never been touched (no deposits, no orders) is not
	// an error: it returns available="0", reserved="0".
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// ListBalances returns the caller's own balances for every asset they
	// hold a nonzero available or reserved amount in.
	ListBalances(ctx context.Context, in *ListBalancesRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error)
	// Deposit credits available funds to a user's balance. There is no
	// external funding source (bank transfer, blockchain deposit) wired
	// into this system, so this is currently the only way funds enter it.
	// Requires ROLE_ADMIN.
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	// Reserve moves amount from available to reserved for the given asset.
	// Called when a limit order is placed, to lock the funds it could
	// consume. Returns FailedPrecondition if available funds are
	// insufficient.
	Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error)
	// ReleaseReservation moves the remaining reserved amount for a
	// reservation back to available. Called when an order is cancelled, or
	// expires with a partially- or wholly-unfilled remainder.
	ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error)
	// SettleReservation permanently debits amount from a reservation.
	// Called by the matching engine when a trade executes against the
	// reserved order. amount may be less than what remains reserved, for a
	// partial fill — the untouched remainder stays reserved for later
	// fills or eventual release.
	SettleReservation(ctx context.Context, in *SettleReservationRequest, opts ...grpc.CallOption) (*SettleReservationResponse, error)
	// Credit adds amount directly to available funds. Called by the
	// matching engine for the counterparty side of a trade — the asset an
	// order was buying, which was never reserved on this side since it's
	// being received, not spent.
	Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error)
}

type walletServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletServiceClient(cc grpc.ClientConnInterface) WalletServiceClient {
	return &walletServiceClient{cc}
}

func (c *walletServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, WalletService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ListBalances(ctx context.Context, in *ListBalancesRequest, opts ...grpc.CallOption) (*ListBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBalancesResponse)
	err := c.cc.Invoke(ctx, WalletService_ListBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, WalletService_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Reserve(ctx context.Context, in *ReserveRequest, opts ...grpc.CallOption) (*ReserveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveResponse)
	err := c.cc.Invoke(ctx, WalletService_Reserve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) ReleaseReservation(ctx context.Context, in *ReleaseReservationRequest, opts ...grpc.CallOption) (*ReleaseReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReservationResponse)
	err := c.cc.Invoke(ctx, WalletService_ReleaseReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) SettleReservation(ctx context.Context, in *SettleReservationRequest, opts ...grpc.CallOption) (*SettleReservationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettleReservationResponse)
	err := c.cc.Invoke(ctx, WalletService_SettleReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletServiceClient) Credit(ctx context.Context, in *CreditRequest, opts ...grpc.CallOption) (*CreditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditResponse)
	err := c.cc.Invoke(ctx, WalletService_Credit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletServiceServer is the server API for WalletService service.
// All implementations must embed UnimplementedWalletServiceServer
// for forward compatibility.
//
// WalletService manages per-user, per-asset balances.
//
// GetBalance/ListBalances/Deposit are called with a normal user access
// token, validated against UserService.ValidateToken exactly like
// SpotInstrumentService/OrderService already do.
//
// Reserve/ReleaseReservation/SettleReservation/Credit are different: they
// are not actions a user takes directly, but internal calls OrderService
// (and, later, its matching engine) makes on a user's behalf while
// processing an order or executing a trade — including at match time,
// which happens asynchronously, outside the lifetime of any single user
// request. Forwarding the original user's access token does not fit this
// pattern. These four RPCs will need a service-to-service credential
// (e.g. a machine account / mTLS) distinct from user JWTs — deliberately
// left as an open question until the calling side (OrderService's
// matching engine) is implemented, rather than guessed at here.
type WalletServiceServer interface {
	// GetBalance returns the caller's own balance for a single asset. A
	// balance that has never been touched (no deposits, no orders) is not
	// an error: it returns available="0", reserved="0".
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// ListBalances returns the caller's own balances for every asset they
	// hold a nonzero available or reserved amount in.
	ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error)
	// Deposit credits available funds to a user's balance. There is no
	// external funding source (bank transfer, blockchain deposit) wired
	// into this system, so this is currently the only way funds enter it.
	// Requires ROLE_ADMIN.
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	// Reserve moves amount from available to reserved for the given asset.
	// Called when a limit order is placed, to lock the funds it could
	// consume. Returns FailedPrecondition if available funds are
	// insufficient.
	Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error)
	// ReleaseReservation moves the remaining reserved amount for a
	// reservation back to available. Called when an order is cancelled, or
	// expires with a partially- or wholly-unfilled remainder.
	ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error)
	// SettleReservation permanently debits amount from a reservation.
	// Called by the matching engine when a trade executes against the
	// reserved order. amount may be less than what remains reserved, for a
	// partial fill — the untouched remainder stays reserved for later
	// fills or eventual release.
	SettleReservation(context.Context, *SettleReservationRequest) (*SettleReservationResponse, error)
	// Credit adds amount directly to available funds. Called by the
	// matching engine for the counterparty side of a trade — the asset an
	// order was buying, which was never reserved on this side since it's
	// being received, not spent.
	Credit(context.Context, *CreditRequest) (*CreditResponse, error)
	mustEmbedUnimplementedWalletServiceServer()
}

// UnimplementedWalletServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletServiceServer struct{}

func (UnimplementedWalletServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedWalletServiceServer) ListBalances(context.Context, *ListBalancesRequest) (*ListBalancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBalances not implemented")
}
func (UnimplementedWalletServiceServer) Deposit(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedWalletServiceServer) Reserve(context.Context, *ReserveRequest) (*ReserveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reserve not implemented")
}
func (UnimplementedWalletServiceServer) ReleaseReservation(context.Context, *ReleaseReservationRequest) (*ReleaseReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseReservation not implemented")
}
func (UnimplementedWalletServiceServer) SettleReservation(context.Context, *SettleReservationRequest) (*SettleReservationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SettleReservation not implemented")
}
func (UnimplementedWalletServiceServer) Credit(context.Context, *CreditRequest) (*CreditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Credit not implemented")
}
func (UnimplementedWalletServiceServer) mustEmbedUnimplementedWalletServiceServer() {}
func (UnimplementedWalletServiceServer) testEmbeddedByValue()                       {}

// UnsafeWalletServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletServiceServer will
// result in compilation errors.
type UnsafeWalletServiceServer interface {
	mustEmbedUnimplementedWalletServiceServer()
}

func RegisterWalletServiceServer(s grpc.ServiceRegistrar, srv WalletServiceServer) {
	// If the following call panics, it indicates UnimplementedWalletServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletService_ServiceDesc, srv)
}

func _WalletService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ListBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ListBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ListBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ListBalances(ctx, req.(*ListBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Reserve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Reserve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Reserve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Reserve(ctx, req.(*ReserveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_ReleaseReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).ReleaseReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_ReleaseReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).ReleaseReservation(ctx, req.(*ReleaseReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_SettleReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettleReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).SettleReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_SettleReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).SettleReservation(ctx, req.(*SettleReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletService_Credit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletServiceServer).Credit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletService_Credit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletServiceServer).Credit(ctx, req.(*CreditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletService_ServiceDesc is the grpc.ServiceDesc for WalletService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walletservice.v1.WalletService",
	HandlerType: (*WalletServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBalance",
			Handler:    _WalletService_GetBalance_Handler,
		},
		{
			MethodName: "ListBalances",
			Handler:    _WalletService_ListBalances_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _WalletService_Deposit_Handler,
		},
		{
			MethodName: "Reserve",
			Handler:    _WalletService_Reserve_Handler,
		},
		{
			MethodName: "ReleaseReservation",
			Handler:    _WalletService_ReleaseReservation_Handler,
		},
		{
			MethodName: "SettleReservation",
			Handler:    _WalletService_SettleReservation_Handler,
		},
		{
			MethodName: "Credit",
			Handler:    _WalletService_Credit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "walletservice/wallet.proto",
}
