// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: userservice/v1/user.proto

// Package userservice.v1 defines the public gRPC contract for UserService:
// registration, authentication, session management and profile operations.

package userv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is the set of permission levels a user account can hold.
type Role int32

const (
	// ROLE_UNSPECIFIED is the zero value and should never be assigned to a
	// real user; its presence in a response indicates a missing or
	// unrecognized role.
	Role_ROLE_UNSPECIFIED Role = 0
	// ROLE_USER is the default role assigned to every new account.
	Role_ROLE_USER Role = 1
	// ROLE_ADMIN grants access to administrative operations such as
	// GetUserProfile, and to write operations in other services (e.g.
	// SpotInstrumentService.CreateInstrument) that check role via
	// ValidateToken.
	Role_ROLE_ADMIN Role = 2
	// ROLE_PREMIUM is reserved for future paid-tier functionality.
	Role_ROLE_PREMIUM Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ADMIN",
		3: "ROLE_PREMIUM",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ADMIN":       2,
		"ROLE_PREMIUM":     3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_userservice_v1_user_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_userservice_v1_user_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{0}
}

// AuthToken is the pair of tokens issued on successful authentication.
type AuthToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// access_token is a short-lived JWT used to authenticate subsequent
	// requests. Passed as "authorization: Bearer <access_token>".
	AccessToken string `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// refresh_token is a long-lived, opaque, single-use token used to obtain
	// a new AuthToken via RefreshToken. Rotated on every use.
	RefreshToken string `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	// expires_at is the expiration timestamp of access_token.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthToken) Reset() {
	*x = AuthToken{}
	mi := &file_userservice_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthToken) ProtoMessage() {}

func (x *AuthToken) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthToken.ProtoReflect.Descriptor instead.
func (*AuthToken) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *AuthToken) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthToken) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *AuthToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RegisterRequest carries the data required to create a new account.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Email string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// password is the plaintext password; never stored or logged as-is.
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

// LoginRequest carries credentials for an existing account.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuthToken     *AuthToken             `protobuf:"bytes,2,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LoginResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

// LogoutRequest identifies the session to revoke by its refresh token.
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{6}
}

// GetProfileRequest is empty: the target user is always the authenticated
// caller, resolved from the access token by the auth interceptor.
type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{7}
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=userservice.v1.Role" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GetProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// GetUserProfileRequest identifies an arbitrary target user by ID.
// Calling this method requires the ROLE_ADMIN role.
type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=userservice.v1.Role" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserProfileResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GetUserProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ChangePasswordRequest carries the current and new password for the
// authenticated caller. user_id is not included: it is resolved from the
// access token.
type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{11}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{12}
}

// RefreshTokenRequest carries the refresh token to exchange for a new
// AuthToken.
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     *AuthToken             `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{14}
}

func (x *RefreshTokenResponse) GetAuthToken() *AuthToken {
	if x != nil {
		return x.AuthToken
	}
	return nil
}

// UpdateProfileRequest partially updates the caller's own profile.
// Unset (nil) fields are left unchanged; fields explicitly set to an empty
// string are rejected by validation.
type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     *string                `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName      *string                `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          Role                   `protobuf:"varint,3,opt,name=role,proto3,enum=userservice.v1.Role" json:"role,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProfileResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateProfileResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *UpdateProfileResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UpdateProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

// ValidateTokenRequest carries an access token to check.
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_userservice_v1_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// valid is false for any invalid or expired token; user_id and role are
	// only meaningful when valid is true.
	Valid         bool   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          Role   `protobuf:"varint,3,opt,name=role,proto3,enum=userservice.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_userservice_v1_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userservice_v1_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_userservice_v1_user_proto_rawDescGZIP(), []int{18}
}

func (x *ValidateTokenResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

var File_userservice_v1_user_proto protoreflect.FileDescriptor

const file_userservice_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x19userservice/v1/user.proto\x12\x0euserservice.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x8e\x01\n" +
	"\tAuthToken\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa3\x01\n" +
	"\x0fRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\bR\bpassword\x12&\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tfirstName\x12$\n" +
	"\tlast_name\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blastName\"e\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x19.userservice.v1.AuthTokenR\tauthToken\"R\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xbaH\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bpassword\"b\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\n" +
	"auth_token\x18\x02 \x01(\v2\x19.userservice.v1.AuthTokenR\tauthToken\"=\n" +
	"\rLogoutRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\frefreshToken\"\x10\n" +
	"\x0eLogoutResponse\"\x13\n" +
	"\x11GetProfileRequest\"\xe4\x01\n" +
	"\x12GetProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.userservice.v1.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\":\n" +
	"\x15GetUserProfileRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x06userId\"\xac\x01\n" +
	"\x16GetUserProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.userservice.v1.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"o\n" +
	"\x15ChangePasswordRequest\x12*\n" +
	"\fold_password\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voldPassword\x12*\n" +
	"\fnew_password\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\bR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse\"C\n" +
	"\x13RefreshTokenRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\frefreshToken\"P\n" +
	"\x14RefreshTokenResponse\x128\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\v2\x19.userservice.v1.AuthTokenR\tauthToken\"\x8b\x01\n" +
	"\x14UpdateProfileRequest\x12+\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x00R\tfirstName\x88\x01\x01\x12)\n" +
	"\tlast_name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01H\x01R\blastName\x88\x01\x01B\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_name\"\xe7\x01\n" +
	"\x15UpdateProfileResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.userservice.v1.RoleR\x04role\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"first_name\x18\x05 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x06 \x01(\tR\blastName\"B\n" +
	"\x14ValidateTokenRequest\x12*\n" +
	"\faccess_token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaccessToken\"p\n" +
	"\x15ValidateTokenResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12(\n" +
	"\x04role\x18\x03 \x01(\x0e2\x14.userservice.v1.RoleR\x04role*M\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x10\n" +
	"\fROLE_PREMIUM\x10\x032\xab\x06\n" +
	"\vUserService\x12O\n" +
	"\bRegister\x12\x1f.userservice.v1.RegisterRequest\x1a .userservice.v1.RegisterResponse\"\x00\x12F\n" +
	"\x05Login\x12\x1c.userservice.v1.LoginRequest\x1a\x1d.userservice.v1.LoginResponse\"\x00\x12I\n" +
	"\x06Logout\x12\x1d.userservice.v1.LogoutRequest\x1a\x1e.userservice.v1.LogoutResponse\"\x00\x12^\n" +
	"\rValidateToken\x12$.userservice.v1.ValidateTokenRequest\x1a%.userservice.v1.ValidateTokenResponse\"\x00\x12U\n" +
	"\n" +
	"GetProfile\x12!.userservice.v1.GetProfileRequest\x1a\".userservice.v1.GetProfileResponse\"\x00\x12a\n" +
	"\x0eGetUserProfile\x12%.userservice.v1.GetUserProfileRequest\x1a&.userservice.v1.GetUserProfileResponse\"\x00\x12^\n" +
	"\rUpdateProfile\x12$.userservice.v1.UpdateProfileRequest\x1a%.userservice.v1.UpdateProfileResponse\"\x00\x12a\n" +
	"\x0eChangePassword\x12%.userservice.v1.ChangePasswordRequest\x1a&.userservice.v1.ChangePasswordResponse\"\x00\x12[\n" +
	"\fRefreshToken\x12#.userservice.v1.RefreshTokenRequest\x1a$.userservice.v1.RefreshTokenResponse\"\x00B\x17Z\x15userservice/v1;userv1b\x06proto3"

var (
	file_userservice_v1_user_proto_rawDescOnce sync.Once
	file_userservice_v1_user_proto_rawDescData []byte
)

func file_userservice_v1_user_proto_rawDescGZIP() []byte {
	file_userservice_v1_user_proto_rawDescOnce.Do(func() {
		file_userservice_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userservice_v1_user_proto_rawDesc), len(file_userservice_v1_user_proto_rawDesc)))
	})
	return file_userservice_v1_user_proto_rawDescData
}

var file_userservice_v1_user_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_userservice_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_userservice_v1_user_proto_goTypes = []any{
	(Role)(0),                      // 0: userservice.v1.Role
	(*AuthToken)(nil),              // 1: userservice.v1.AuthToken
	(*RegisterRequest)(nil),        // 2: userservice.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 3: userservice.v1.RegisterResponse
	(*LoginRequest)(nil),           // 4: userservice.v1.LoginRequest
	(*LoginResponse)(nil),          // 5: userservice.v1.LoginResponse
	(*LogoutRequest)(nil),          // 6: userservice.v1.LogoutRequest
	(*LogoutResponse)(nil),         // 7: userservice.v1.LogoutResponse
	(*GetProfileRequest)(nil),      // 8: userservice.v1.GetProfileRequest
	(*GetProfileResponse)(nil),     // 9: userservice.v1.GetProfileResponse
	(*GetUserProfileRequest)(nil),  // 10: userservice.v1.GetUserProfileRequest
	(*GetUserProfileResponse)(nil), // 11: userservice.v1.GetUserProfileResponse
	(*ChangePasswordRequest)(nil),  // 12: userservice.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 13: userservice.v1.ChangePasswordResponse
	(*RefreshTokenRequest)(nil),    // 14: userservice.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 15: userservice.v1.RefreshTokenResponse
	(*UpdateProfileRequest)(nil),   // 16: userservice.v1.UpdateProfileRequest
	(*UpdateProfileResponse)(nil),  // 17: userservice.v1.UpdateProfileResponse
	(*ValidateTokenRequest)(nil),   // 18: userservice.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 19: userservice.v1.ValidateTokenResponse
	(*timestamppb.Timestamp)(nil),  // 20: google.protobuf.Timestamp
}
var file_userservice_v1_user_proto_depIdxs = []int32{
	20, // 0: userservice.v1.AuthToken.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 1: userservice.v1.RegisterResponse.auth_token:type_name -> userservice.v1.AuthToken
	1,  // 2: userservice.v1.LoginResponse.auth_token:type_name -> userservice.v1.AuthToken
	0,  // 3: userservice.v1.GetProfileResponse.role:type_name -> userservice.v1.Role
	20, // 4: userservice.v1.GetProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 5: userservice.v1.GetUserProfileResponse.role:type_name -> userservice.v1.Role
	20, // 6: userservice.v1.GetUserProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	1,  // 7: userservice.v1.RefreshTokenResponse.auth_token:type_name -> userservice.v1.AuthToken
	0,  // 8: userservice.v1.UpdateProfileResponse.role:type_name -> userservice.v1.Role
	20, // 9: userservice.v1.UpdateProfileResponse.created_at:type_name -> google.protobuf.Timestamp
	0,  // 10: userservice.v1.ValidateTokenResponse.role:type_name -> userservice.v1.Role
	2,  // 11: userservice.v1.UserService.Register:input_type -> userservice.v1.RegisterRequest
	4,  // 12: userservice.v1.UserService.Login:input_type -> userservice.v1.LoginRequest
	6,  // 13: userservice.v1.UserService.Logout:input_type -> userservice.v1.LogoutRequest
	18, // 14: userservice.v1.UserService.ValidateToken:input_type -> userservice.v1.ValidateTokenRequest
	8,  // 15: userservice.v1.UserService.GetProfile:input_type -> userservice.v1.GetProfileRequest
	10, // 16: userservice.v1.UserService.GetUserProfile:input_type -> userservice.v1.GetUserProfileRequest
	16, // 17: userservice.v1.UserService.UpdateProfile:input_type -> userservice.v1.UpdateProfileRequest
	12, // 18: userservice.v1.UserService.ChangePassword:input_type -> userservice.v1.ChangePasswordRequest
	14, // 19: userservice.v1.UserService.RefreshToken:input_type -> userservice.v1.RefreshTokenRequest
	3,  // 20: userservice.v1.UserService.Register:output_type -> userservice.v1.RegisterResponse
	5,  // 21: userservice.v1.UserService.Login:output_type -> userservice.v1.LoginResponse
	7,  // 22: userservice.v1.UserService.Logout:output_type -> userservice.v1.LogoutResponse
	19, // 23: userservice.v1.UserService.ValidateToken:output_type -> userservice.v1.ValidateTokenResponse
	9,  // 24: userservice.v1.UserService.GetProfile:output_type -> userservice.v1.GetProfileResponse
	11, // 25: userservice.v1.UserService.GetUserProfile:output_type -> userservice.v1.GetUserProfileResponse
	17, // 26: userservice.v1.UserService.UpdateProfile:output_type -> userservice.v1.UpdateProfileResponse
	13, // 27: userservice.v1.UserService.ChangePassword:output_type -> userservice.v1.ChangePasswordResponse
	15, // 28: userservice.v1.UserService.RefreshToken:output_type -> userservice.v1.RefreshTokenResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_userservice_v1_user_proto_init() }
func file_userservice_v1_user_proto_init() {
	if File_userservice_v1_user_proto != nil {
		return
	}
	file_userservice_v1_user_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userservice_v1_user_proto_rawDesc), len(file_userservice_v1_user_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userservice_v1_user_proto_goTypes,
		DependencyIndexes: file_userservice_v1_user_proto_depIdxs,
		EnumInfos:         file_userservice_v1_user_proto_enumTypes,
		MessageInfos:      file_userservice_v1_user_proto_msgTypes,
	}.Build()
	File_userservice_v1_user_proto = out.File
	file_userservice_v1_user_proto_goTypes = nil
	file_userservice_v1_user_proto_depIdxs = nil
}
